#! /usr/bin/bash


usage()
{
cat <<EOF
catlog <shiny_app_name>
EOF
}

if [ "$1" == "" ]; then
	usage
	exit 1
fi

app_name=$1
sudo docker exec --workdir /var/log/shiny-server -it ${app_name} bash -c "cat \`ls -Art | tail -n 1\`"